[server]
# Aktiviert den Headless-Modus, erforderlich für die Ausführung auf Streamlit Cloud.
headless = true

# Verhindert Cross-Origin Resource Sharing (CORS)-Probleme.
enableCORS = false

# Optimiert die Serverleistung durch Anpassung der Websocket-Ping-Einstellungen.
websocketPingTimeout = 180
websocketPingInterval = 90

# Verhindert, dass die Anwendung automatisch im Browser geöffnet wird.
browser.gatherUsageStats = false

[theme]
# Definiert das Farbschema der Anwendung für bessere Benutzerfreundlichkeit.
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"
